import {} from 'module';
import {} from 'module';
import {} from 'module';
import {} from 'module';
import {} from 'module';
import {} from 'module';
import {} from 'module';
import {} from 'module';
import {} from 'module';
import {} from 'module';
import {} from 'module';
import {} from 'module';
import {} from 'module';
import {} from 'module';
import {} from 'module';
import {} from 'module';
import {} from 'module';
import {} from 'module';
import {} from 'module';
import {} from 'module';
import {} from 'module';
import {} from 'module';
import {} from 'module';
import {} from 'module';
function name(params) {}
console.log('11');
